# Generated by Django 3.2.18 on 2023-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image_url',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
