# Generated by Django 3.2.18 on 2023-03-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoastingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='coffee_beans/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flavor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.flavorprofile')),
                ('roasting_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.roastinglevel')),
            ],
        ),
    ]
