# Generated by Django 3.2.18 on 2023-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230331_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebean',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
